<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-BUCV5FUF" failures="1" tests="5" name="Personal Loan" time="0.048" errors="0" timestamp="2023-04-18T17:36:00 IST">
  <testcase classname="test.testPractice" name="Demo" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.testPractice.Demo(testPractice.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.testPractice2" name="ploan" time="0.001"/>
  <testcase classname="test.testPractice4" name="apiLoginHomeLoan" time="0.001"/>
  <testcase classname="test.testPractice4" name="mobileLoginHomeLoan" time="0.001"/>
  <testcase classname="test.testPractice4" name="webLoginHomeLoan" time="0.001"/>
  <testcase classname="test.testPractice" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
